import type { IngredientCategory } from '@kitchen/contracts';
import type { IllustrationName } from '../components/glyphs/illustration-paths';
import type { FoodIconKey } from './food-icon';

export const FOOD_CATEGORY_ILLUSTRATION = {
  vegetable: 'carrot',
  fruit: 'carrot',
  meat: 'chicken',
  poultry: 'chicken',
  seafood: 'chicken',
  dairy: 'milk',
  egg: 'egg',
  grain: 'bread',
  legume: 'plate',
  pasta: 'bread',
  bread: 'bread',
  spice: 'spice',
  herb: 'herb',
  condiment: 'plate',
  oil: 'oil',
  sweetener: 'plate',
  nut: 'plate',
  beverage: 'glass',
  frozen: 'freezer',
  canned: 'plate',
  baking: 'bread',
  other: 'plate',
} satisfies Record<IngredientCategory, IllustrationName>;

export const FOOD_ILLUSTRATION = {
  apple: 'apple',
  banana: 'carrot',
  basket: 'plate',
  beans: 'plate',
  bread: 'bread',
  butter: 'milk',
  cake: 'bread',
  candy: 'plate',
  canned: 'plate',
  carrot: 'carrot',
  cereal: 'bread',
  cheese: 'cheese',
  chicken: 'chicken',
  chocolate: 'plate',
  coffee: 'glass',
  cookie: 'bread',
  croissant: 'bread',
  cucumber: 'carrot',
  egg: 'egg',
  fish: 'chicken',
  flour: 'bread',
  frozen: 'freezer',
  garlic: 'garlic',
  grapes: 'carrot',
  herbs: 'herb',
  honey: 'plate',
  icecream: 'milk',
  juice: 'glass',
  lemon: 'lemon',
  mango: 'carrot',
  meat: 'chicken',
  milk: 'milk',
  nuts: 'plate',
  oliveoil: 'oil',
  onion: 'onion',
  orange: 'carrot',
  pasta: 'bread',
  peach: 'carrot',
  pepper: 'spice',
  pizza: 'bread',
  potato: 'potato',
  pudding: 'milk',
  rice: 'rice',
  salad: 'carrot',
  salt: 'salt',
  sandwich: 'bread',
  shrimp: 'chicken',
  strawberry: 'carrot',
  tea: 'glass',
  tomato: 'tomato',
  water: 'glass',
  watermelon: 'carrot',
} satisfies Record<FoodIconKey, IllustrationName>;
